### ISSUE TITLE
add codechef stars colour

### ISSUE THREAD

**Issue by akashh369** [akashh369/CPUnified-client#1]
<img width="1439" alt="Screenshot 2024-03-30 at 11 44 30 AM" src="https://github.com/akashh369/CPUnified-client/assets/104349892/0d8cd30d-a086-4c1e-806a-7bcfd6d31694">

here make the colours of codechef stars change according to the original codechef website

**Comment by Yogendra213** [comment]
Please assign this issue to me

**Comment by akashh369** [comment]
> Please assign this issue to me

take this new branch "1-add-codechef-stars-colour"
